spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev  #開發環境
  application:
    name: microservicecloud-config-jacob-dev
---
spring:
  profiles: test #測試環境
  application:
    name: microservicecloud-config-jacob-test
#請儲存為UTF-8格式