spring:
  profiles:
    active:
    - dev
---
server:
    port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: org.gjt.mm.mysql.Driver
   url: jdbc:mysql://localhost:3306/jacob?useSSL=false
   username: Jacob
   password: 1234
   dbcp2:
     min-idle: 5
     initial: 5
     max-total: 5
     max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml     #mybatis配置文件所在路徑
  type-aliases-package: com.jacob.springcloud.entities   #所有Entity別名類所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                    #mapper映射文件
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com #status的默認名稱修改
    prefer-ip-address: true #訪問路徑可以顯示IP地址
    
info:
  app:
    name: jacob-microservicecloud-springcloudconfig01
  company:
    name: www.javob.com
  build:
    artifactId: $project.artifactId$
    version: $project.version$
---
server:
    port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: org.gjt.mm.mysql.Driver
   url: jdbc:mysql://localhost:3306/jacob?useSSL=false
   username: Jacob
   password: 1234
   dbcp2:
     min-idle: 5
     initial: 5
     max-total: 5
     max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml     #mybatis配置文件所在路徑
  type-aliases-package: com.jacob.springcloud.entities   #所有Entity別名類所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                    #mapper映射文件
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com #status的默認名稱修改
    prefer-ip-address: true #訪問路徑可以顯示IP地址
    
info:
  app:
    name: jacob-microservicecloud-springcloudconfig01
  company:
    name: www.javob.com
  build:
    artifactId: $project.artifactId$
    version: $project.version$